In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pcs
import cirq
import qudit_gates as qg
import numpy as np

In [3]:
qudits = [cirq.LineQid(i, dimension=3) for i in range(2)]

ancilla_qubit = cirq.LineQubit(2)

error_moment = cirq.Moment(qg.QutritDepolarizingChannel(0.01).on(qudits[1]), qg.QutritDepolarizingChannel(0.01).on(qudits[0]))

noisy_circuit_qubit_ancilla = cirq.Circuit(cirq.H(ancilla_qubit), qg.QutritZZGate().on(qudits[0], qudits[1]).controlled_by(ancilla_qubit),
                             qg.QutritCZGate().on(qudits[0], qudits[1]), 
                             error_moment, qg.QutritCZGate().on(qudits[0], qudits[1]),
                             error_moment, qg.QutritCZGate().on(qudits[0], qudits[1]), 
                             error_moment,qg.QutritZZGate().on(qudits[0], qudits[1]).controlled_by(ancilla_qubit), 
                             cirq.H(ancilla_qubit), cirq.Moment(cirq.measure_each(*qudits), cirq.measure(ancilla_qubit)))

In [65]:
noisy_circuit_qubit_ancilla

0 (d=3): ───────#2──────────────────────────────────────────────────TCZ───D3(0.01)───TCZ───D3(0.01)───TCZ───D3(0.01)───#2──────────────────────────────────────────────────────M───
                │                                                   │                │                │                │
1 (d=3): ───────#3──────────────────────────────────────────────────TCZ───D3(0.01)───TCZ───D3(0.01)───TCZ───D3(0.01)───#3──────────────────────────────────────────────────────M───
                │                                                                                                      │
2: ─────────H───C<qudit_gates.QutritZZGate object at 0x156307ec0>──────────────────────────────────────────────────────C<qudit_gates.QutritZZGate object at 0x156305be0>───H───M───

In [66]:
pcs.simulate_noisy_circuit(noisy_circuit_qubit_ancilla, shots=100000)

Counter({(0, 0, 0): 95614, (0, 1, 1): 2220, (1, 0, 1): 2110, (1, 1, 0): 56})

In [31]:
qudits = [cirq.LineQid(i, dimension=3) for i in range(2)]
error_moment = cirq.Moment(qg.QutritDepolarizingChannel(0.01).on(qudits[1]))

noisy_circuit_qutrit_ancilla = cirq.Circuit(qg.QutritChrestensonGate().on(qudits[1]), 
                             qg.QutritZGate().on(qudits[0]).controlled_by(qudits[1]),
                             qg.QutritPlusGate().on(qudits[0]),qg.QutritPlusGate().on(qudits[0]).controlled_by(qudits[1]), 
                             qg.QutritChrestensonGate().on(qudits[1]), cirq.Moment(cirq.measure_each(*qudits)))

In [55]:
noisy_circuit_qubit_ancilla = cirq.Circuit(cirq.H(ancilla_qubit), qg.ErrorZGate().on(qudits[0]).controlled_by(ancilla_qubit),
                             qg.QutritPlusGate().on(qudits[0]),qg.ErrorZ2Gate().on(qudits[0]).controlled_by(ancilla_qubit), cirq.H(ancilla_qubit),
                            cirq.Moment(cirq.measure_each(qudits[0], ancilla_qubit)))

In [56]:
noisy_circuit_qubit_ancilla

0 (d=3): ───────#2────────────────────────────────────────────────[+]───#2─────────────────────────────────────────────────────M───
                │                                                       │
2: ─────────H───C<qudit_gates.ErrorZGate object at 0x153d8e8a0>─────────C<qudit_gates.ErrorZ2Gate object at 0x154aaf3e0>───H───M───

In [57]:
pcs.simulate_noisy_circuit(noisy_circuit_qubit_ancilla, shots=100000)

Counter({(1, 1): 75082, (1, 0): 24918})

In [41]:
qudits = [cirq.LineQid(i, dimension=3) for i in range(3)]
error_moment = cirq.Moment(qg.QutritDepolarizingChannel(0.01).on(qudits[0]), qg.QutritDepolarizingChannel(0.01).on(qudits[1]))



identity_qutrit_circuit = cirq.Circuit(
                            qg.QutritChrestensonGate().on(qudits[2]),
                            qg.QutritZZGate().on(qudits[0], qudits[1]).controlled_by(qudits[2]), 
                            error_moment, qg.QutritIdentityGate().on_each(*qudits), 
                            error_moment, qg.QutritIdentityGate().on_each(*qudits),
                            error_moment, qg.QutritIdentityGate().on_each(*qudits),
                            qg.QutritZZGate().on(qudits[0], qudits[1]).controlled_by(qudits[2]), 
                            qg.QutritChrestensonGate().on(qudits[2]), cirq.Moment(cirq.measure_each(*qudits)))


print(identity_qutrit_circuit)
                            
                            

0 (d=3): ────────#2──────────────────────────────────────────────────D3(0.01)───I3───D3(0.01)───I3───D3(0.01)───I3───#2───────────────────────────────────────────────────────M───
                 │                                                                                                   │
1 (d=3): ────────#3──────────────────────────────────────────────────D3(0.01)───I3───D3(0.01)───I3───D3(0.01)───I3───#3───────────────────────────────────────────────────────M───
                 │                                                                                                   │
2 (d=3): ───C3───C<qudit_gates.QutritZZGate object at 0x1561e3e90>───I3─────────I3───I3──────────────────────────────C<qudit_gates.QutritZZGate object at 0x1561e3c80>───C3───M───


In [42]:
pcs.simulate_noisy_circuit(identity_qutrit_circuit, shots=100000)

Counter({(0, 0, 0): 95650,
         (1, 1, 0): 1940,
         (1, 0, 1): 1880,
         (0, 1, 0): 255,
         (0, 0, 1): 238,
         (0, 1, 1): 37})

In [27]:
qudits = [cirq.LineQid(i, dimension=3) for i in range(2)]

ancilla_ququart = cirq.LineQid(2, dimension=4)

error_moment = cirq.Moment(qg.QutritDepolarizingChannel(0.01).on(qudits[1]), qg.QutritDepolarizingChannel(0.01).on(qudits[0]))

noisy_circuit_ququart_ancilla = cirq.Circuit(qg.QuquartChrestensonGate().on(ancilla_ququart), 
                             qg.QutritZZGate().on(qudits[0], qudits[1]).controlled_by(ancilla_ququart),
                             qg.QutritCZGate().on(qudits[0], qudits[1]), 
                             error_moment, qg.QutritCZGate().on(qudits[0], qudits[1]),
                             error_moment, qg.QutritCZGate().on(qudits[0], qudits[1]), 
                             error_moment, qg.QutritZZGate().on(qudits[0], qudits[1]).controlled_by(ancilla_ququart), 
                             qg.QuquartChrestensonGate().on(ancilla_ququart), 
                             cirq.Moment(cirq.measure_each(*qudits), cirq.measure(ancilla_ququart)))

In [28]:
noisy_circuit_ququart_ancilla

0 (d=3): ────────#2──────────────────────────────────────────────────TCZ───D3(0.01)───TCZ───D3(0.01)───TCZ───D3(0.01)───#2───────────────────────────────────────────────────────M───
                 │                                                   │                │                │                │
1 (d=3): ────────#3──────────────────────────────────────────────────TCZ───D3(0.01)───TCZ───D3(0.01)───TCZ───D3(0.01)───#3───────────────────────────────────────────────────────M───
                 │                                                                                                      │
2 (d=4): ───C4───C<qudit_gates.QutritZZGate object at 0x1560a9af0>──────────────────────────────────────────────────────C<qudit_gates.QutritZZGate object at 0x1560a95b0>───C4───M───

In [29]:
pcs.simulate_noisy_circuit(noisy_circuit_ququart_ancilla, shots=100000)

Counter({(0, 0, 0): 95575,
         (1, 1, 0): 1672,
         (1, 0, 1): 1614,
         (0, 1, 0): 579,
         (0, 0, 1): 520,
         (0, 1, 1): 40})

In [ ]:
qubits = cirq.LineQubit.range(2)
ancilla_qudit = cirq.LineQid(2, dimension=3)

circuit = cirq.Circuit(
            qg.QutritChrestensonGate().on(ancilla_qudit), cirq.PauliString(cirq.Z(qubits[0]), 
            cirq.Z(qubits[1])).controlled_by(ancilla_qudit),
            cirq.CZ(qubits[0], qubits[1]), cirq.CZ(qubits[0], qubits[1]), 
            cirq.CZ(qubits[0], qubits[1]), 
            cirq.PauliString(cirq.Z(qubits[0]), cirq.Z(qubits[1])).controlled_by(ancilla_qudit), 
            qg.QutritChrestensonGate().on(ancilla_qudit), cirq.Moment(cirq.measure_each(*qubits), cirq.measure(ancilla_qudit)))

circuit

In [ ]:
noisy_circuit = pcs.create_noisy_circuit(circuit, noisy_qubits=[qubits[1]])

In [ ]:
pcs.simulate_noisy_circuit(noisy_circuit, shots = 100000)

In [30]:
qubits = cirq.LineQubit.range(2)
ancilla_ququart = cirq.LineQid(2, dimension=4)

circuit = cirq.Circuit(
            qg.QuquartChrestensonGate().on(ancilla_ququart), cirq.PauliString(cirq.Z(qubits[0]), 
            cirq.Z(qubits[1])).controlled_by(ancilla_ququart),
            cirq.CZ(qubits[0], qubits[1]), cirq.CZ(qubits[0], qubits[1]), 
            cirq.CZ(qubits[0], qubits[1]), 
            cirq.PauliString(cirq.Z(qubits[0]), cirq.Z(qubits[1])).controlled_by(ancilla_ququart), 
            qg.QuquartChrestensonGate().on(ancilla_ququart), cirq.Moment(cirq.measure_each(*qubits), cirq.measure(ancilla_ququart)))

In [31]:
circuit

0: ──────────────PauliString(+Z)───@───@───@───PauliString(+Z)────────M───
                 │                 │   │   │   │
1: ──────────────Z─────────────────@───@───@───Z──────────────────────M───
                 │                             │
2 (d=4): ───C4───@─────────────────────────────@─────────────────C4───M───

In [36]:
noisy_circuit = pcs.create_noisy_circuit(circuit, noisy_qubits=[qubits[0], qubits[1]])

In [37]:
pcs.simulate_noisy_circuit(noisy_circuit, shots = 100000)

Counter({(0, 0, 0): 96026,
         (1, 0, 1): 1497,
         (1, 1, 0): 1431,
         (0, 0, 1): 508,
         (0, 1, 0): 501,
         (0, 1, 1): 37})

In [59]:
qudits = [cirq.LineQid(i, dimension=3) for i in range(2)]
error_moment = cirq.Moment(qg.QutritDepolarizingChannel(0.1).on(qudits[0]))

noisy_circuit_qutrit_ancilla = cirq.Circuit(qg.QutritChrestensonGate().on(qudits[1]), 
                             qg.QutritCZGate().on(qudits[1], qudits[0]),
                             qg.QutritIdentityGate().on(qudits[0]), 
                             error_moment, qg.QutritCZGate().on(qudits[1], qudits[0]), 
                             qg.QutritChrestensonGate().on(qudits[1]))

In [37]:
noisy_circuit_qutrit_ancilla

0 (d=3): ────────TCZ───I3───D3(0.1)───TCZ────────M───
                 │                    │
1 (d=3): ───C3───TCZ──────────────────TCZ───C3───M───

In [38]:
pcs.simulate_noisy_circuit(noisy_circuit_qutrit_ancilla, shots = 100000)

Counter({(0, 0): 92578, (1, 1): 6588, (1, 0): 834})

In [17]:
qg.QutritZGate().on(qudits[0]).controlled_by(qudits[1]).gate._unitary_()

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1]])

In [43]:
type(qg.QutritDepolarizingChannel)

cirq.value.abc_alt.ABCMetaImplementAnyOneOf

In [38]:
omega = np.exp(1j * 2 / 3 * np.pi)

In [22]:
chrestenson = (1/np.sqrt(3))*np.array([[1, 1, 1],
            [1, omega, omega**2],
            [1, omega**2, omega**4]])

In [43]:
state_vector = (1/np.sqrt(3))*np.array([1,-1,1])

In [69]:
chrestenson @ state_vector / (1/(3))

array([1.+0.j        , 1.-1.73205081j, 1.+1.73205081j])

In [54]:
chrestenson

array([[ 0.57735027+0.j ,  0.57735027+0.j ,  0.57735027+0.j ],
       [ 0.57735027+0.j , -0.28867513+0.5j, -0.28867513-0.5j],
       [ 0.57735027+0.j , -0.28867513-0.5j, -0.28867513+0.5j]])

In [35]:
alpha = 0.5*np.sqrt(2)

In [36]:
matrix = np.array([[0,alpha, alpha],
          [alpha, -alpha, 0],
          [alpha, 0, -alpha]])

In [32]:
np.transpose(matrix)

array([[ 0.       ,  0.8660254,  0.8660254],
       [ 0.8660254, -0.8660254,  0.       ],
       [ 0.8660254,  0.       , -0.8660254]])

In [37]:
np.transpose(matrix) @ matrix

array([[ 1. , -0.5, -0.5],
       [-0.5,  1. ,  0.5],
       [-0.5,  0.5,  1. ]])

In [56]:
c1 = 1/np.sqrt(3) * np.array([[1, 1, 1],
                             [1, omega, omega**2],
                             [1, omega**2, omega]])

vector3 = 1/np.sqrt(3) * np.array([1, omega, omega**2])

c1 @ vector3

array([-7.11453991e-18+1.19609907e-16j,  1.66533454e-16+1.06728500e-16j,
        1.00000000e+00-3.37360710e-16j])

In [53]:
c4 = 0.5 * np.array(
            [[1, 1, 1, 1],
            [1, 1j, -1, -1j],
            [1, -1, 1, -1],
            [1, -1j, -1, 1j],
        ])


vector4 = 0.5 * np.array([1,-1j,-1,1j])

In [54]:
c4  @ vector4

array([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j])